[package]
name = "spotifyQL"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
open = "5.3.3"
ring = "0.17.14"
tokio = {version = "1.48.0", features = ["rt", "rt-multi-thread"]}
warp = { version = "0.4.2", features = ["server"] }
